---
name: Docker Image CI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: nolte
      IMAGE_NAME: mosquitto-exporter

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildx-version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
           image: tonistiigi/binfmt:latest
           platforms: all

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine tag
        run: |
          echo "::set-env name=IMAGE_TAG::${GITHUB_REF#refs/tags/}"

      - name: Build and push container image
        run: |
          docker buildx build \
          -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest" \
          -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}" \
          --platform linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -f Dockerfile \
          .